name: Bug report 🐛
description:
  Something isn't working as expected? Here's the right place to report.
title: '[YOUR TITLE]: Brief description'
assignees:
  - oliviaflory,RichKummer
labels: [ 'bug' ]
body:
  - type: markdown
    attributes:
      value: '## Bug report 🐛'
  - type: markdown
    attributes:
      value: 'Use the form below to report any bugs you find on the Carbon for IBM.com website. Feel free to leave blank any sections that aren’t relevant but try to include as much detail as possible. The more details we have, the faster we can respond.'
  - type: markdown
    attributes:
      value: 'If this is an issue for Carbon for IBM.com and not the website, please open an issue at https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/new/choose.'
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What did you expect to happen? What happened instead?"
    validations:
      required: true
  - type: textarea
    id: components
    attributes:
      label: Page(s) impacted
      description: "Page(s) impacted? Please include screenshots, or code and relevant URLs."
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: "What browser(s) are you working in?"
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce the issue (if applicable)"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues) for
            duplicate issues.
